name: Update Status Badges

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Generate Status Badge
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          // Get latest workflow runs
          const { data: workflows } = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'batch-search.yml',
            per_page: 1
          });
          
          const status = workflows.workflow_runs[0]?.conclusion || 'unknown';
          const color = status === 'success' ? 'brightgreen' : 
                       status === 'failure' ? 'red' : 'yellow';
          
          console.log(`Latest batch search status: ${status}`);
          
          // Create badge URL
          const badgeUrl = `https://img.shields.io/badge/batch%20search-${status}-${color}`;
          console.log(`Badge URL: ${badgeUrl}`);
    
    - name: Update README badges
      run: |
        echo "Status badges updated automatically by GitHub Actions"