name: Weekly Comprehensive Search

on:
  schedule:
    # Run every Sunday at 9 AM UTC
    - cron: '0 9 * * 0'
  workflow_dispatch:

jobs:
  comprehensive-search:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create environment file
      run: |
        echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" > .env
        
    - name: Setup Gmail API credentials
      run: |
        echo '${{ secrets.GMAIL_CREDENTIALS }}' > credentials.json
        echo '${{ secrets.GMAIL_TOKEN }}' > token.json
        
    - name: Run comprehensive search with reviews
      run: |
        python cli.py --zip-batch --keywords "charity,food bank,shelter,blood bank,homeless shelter,soup kitchen" --max-results 15 --include-reviews --email --quiet
        
    - name: Archive comprehensive results
      uses: actions/upload-artifact@v4
      with:
        name: weekly-comprehensive-results-${{ github.run_number }}
        path: |
          donation_opportunities_*.json
          donation_opportunities_*.csv
        retention-days: 90
        
    - name: Clean up
      if: always()
      run: |
        rm -f .env credentials.json token.json